### ISSUE TITLE
Extended to load .obj file?

### ISSUE THREAD

**Issue by kaedynrao** [mcoder2014/voxelization#2]
I am trying to load the obj file instead of ply file but it shows an error that ''module' object is not callable'. Are there any solutions to adapt to obj files? Thanks.

Also even if I load the ply file, it shows the same error...

**Comment by mcoder2014** [comment]
Maybe you did not install the `pyassimp3 libs` successfully.<br>
To install this lib, you need to follow those steps below:
1. Install assimp follow this [introduction](https://github.com/assimp/assimp/blob/master/Build.md)
2. [Install PyAssimp port](https://github.com/assimp/assimp/tree/master/port/PyAssimp) ,so you can use python script to run the c++ codes.
